[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.23"
syn = { version = "1.0.100", features = ["full", "extra-traits"] }
wasm-bindgen = "0.2.84"
