[package]
name = "crates"
version = "0.1.0"
edition = "2021"

[dependencies]
get_if_addrs = "0.5.3"
public-ip = "0.2.2"
tokio = { version = "1.25.0", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
