// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: stream.proto

package protoconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	proto "github.com/ever0de/playground/buf-proto/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// ServiceName is the fully-qualified name of the Service service.
	ServiceName = "example.Service"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServiceSubscribeProcedure is the fully-qualified name of the Service's Subscribe RPC.
	ServiceSubscribeProcedure = "/example.Service/Subscribe"
)

// ServiceClient is a client for the example.Service service.
type ServiceClient interface {
	Subscribe(context.Context, *connect_go.Request[proto.SubscriptionRequest]) (*connect_go.ServerStreamForClient[proto.SubscriptionResponse], error)
}

// NewServiceClient constructs a client for the example.Service service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) ServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &serviceClient{
		subscribe: connect_go.NewClient[proto.SubscriptionRequest, proto.SubscriptionResponse](
			httpClient,
			baseURL+ServiceSubscribeProcedure,
			opts...,
		),
	}
}

// serviceClient implements ServiceClient.
type serviceClient struct {
	subscribe *connect_go.Client[proto.SubscriptionRequest, proto.SubscriptionResponse]
}

// Subscribe calls example.Service.Subscribe.
func (c *serviceClient) Subscribe(ctx context.Context, req *connect_go.Request[proto.SubscriptionRequest]) (*connect_go.ServerStreamForClient[proto.SubscriptionResponse], error) {
	return c.subscribe.CallServerStream(ctx, req)
}

// ServiceHandler is an implementation of the example.Service service.
type ServiceHandler interface {
	Subscribe(context.Context, *connect_go.Request[proto.SubscriptionRequest], *connect_go.ServerStream[proto.SubscriptionResponse]) error
}

// NewServiceHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewServiceHandler(svc ServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle(ServiceSubscribeProcedure, connect_go.NewServerStreamHandler(
		ServiceSubscribeProcedure,
		svc.Subscribe,
		opts...,
	))
	return "/example.Service/", mux
}

// UnimplementedServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedServiceHandler struct{}

func (UnimplementedServiceHandler) Subscribe(context.Context, *connect_go.Request[proto.SubscriptionRequest], *connect_go.ServerStream[proto.SubscriptionResponse]) error {
	return connect_go.NewError(connect_go.CodeUnimplemented, errors.New("example.Service.Subscribe is not implemented"))
}
