name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup rtx
        # TODO:
        # uses: jdxcode/rtx-action@v1
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Build
        run: |
          cd go 
          go build -v ./...
          go test -v ./...
